version: "3.7"
services:
  database:
    image: postgres:latest
    restart: always
    ports:
      - "5437:5432"
    # volumes:
    #   - data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: hakaton_bd
      POSTGRES_USER: postgres
      PGDATA: "/var/lib/postgresql/data/pgdata"
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    networks:
      - default
    ports:
      - "8082:8080"
  # minio:
  #   image: minio/minio
  #   restart: always
  #   ports:
  #     - "9000:9000"
  #     - "9001:9001"
  #   # expose:
  #   #   - "9000"
  #   volumes:
  #     - minio_storage:/data
  #   environment:
  #     MINIO_ROOT_USER: user123
  #     MINIO_ROOT_PASSWORD: user123
  #     # MINIO_ACCESS_KEY: 9bRsbGFyUuLX28xGFFA5
  #     # MINIO_SECRET_KEY: o2SfB5LEnNv1o1vVClz16KeSUlbMrQiykjUtbZCT
  #   command: server --console-address ":9001" /data
# volumes:
#   data:
